version: "3.8"
services:
  db:
    image: mysql:8.2.0
    cap_add:
      - SYS_NICE
    restart: on-failure
    hostname: db
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "3307:3306"
volumes:
  db:
    driver: local
